n = input().lower()

n = n.replace("a", "@")
n = nreplace("b", "8")
n = n.replace("c", "(")
n = n.replace("d", "|)")
n = n.replace("e", "3")
n = n.replace("f", "#")
n = n.replace("g", "6")
n = n.replace("h", "[-]")
n = n.replace("i", "|")
n = n.replace("j", "_|")
n = n.replace("k", "|<")
n = n.replace("l", "1")
n = n.replace("m", "[]\\/[]")
n = n.replace("n", "[]\\[]")
n = n.replace("o", "0")
n = n.replace("p", "|D")
n = n.replace("q", "(,)")
n = n.replace("r", "|Z")
n = n.replace("s", "$")
n = n.replace("t", "']['")
n = n.replace("u", "|_|")
n = n.replace("v", "\\/")
n = n.replace("w", "\\/\\/")
n = n.replace("x", "}{")
n = n.replace("y", "`/")
n = n.replace("z", "2")

print(n)
